Repository kut7728/Pinit, pull requests merged in 2025-03, with the labels that each got.

#11 [FEAT] #6 View Handling PinEdit part by HISEHOONAN
  .gitignore
  Pinit/Pinit.xcodeproj/project.pbxproj
  Pinit/Pinit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pinit/Pinit/Extensions/Extension_Bundle.swift
  Pinit/Pinit/Extensions/Extension_UIColor.swift
  Pinit/Pinit/Extensions/Extension_UIView.swift
  Pinit/Pinit/Models/WeatherModel.swift
  Pinit/Pinit/Repository/Moya/Network.swift
  Pinit/Pinit/Repository/Moya/Router.swift
  Pinit/Pinit/Resources/API_KEY.plist
  Pinit/Pinit/Views/PastPin/PastPinViewController.swift
  Pinit/Pinit/Views/PinEdit/PinEditViewController.swift
Labels: FEAT

#12 PinEditViewController 뷰 구현
  .gitignore
  Pinit/Pinit/Views/PinEdit/PinEditViewController.swift
Labels: FEAT

#14 Coredata CRUD 구현
  Pinit/Pinit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Pinit/Pinit/Extensions/Extension_UIViewController.swift
  Pinit/Pinit/Pinit.xcdatamodeld/Pinit.xcdatamodel/contents
  Pinit/Pinit/Repository/CoreData/DBRepository.swift
  Pinit/Pinit/Repository/CoreData/PinDTO+CoreDataClass.swift
  Pinit/Pinit/Repository/CoreData/Pinit.xcdatamodeld/.xccurrentversion
  Pinit/Pinit/Repository/CoreData/Pinit.xcdatamodeld/Pinit.xcdatamodel/contents
  Pinit/Pinit/Repository/CoreData/ReviewDTO+CoreDataClass.swift
  Pinit/Pinit/Views/Home/HomeViewController.swift
Labels: FEAT

#17 Feature/#7 프로필뷰 구현완료
  Pinit/Pinit/Models/ProducerEntity.swift
  Pinit/Pinit/Resources/Assets.xcassets/HISEHOONImg.imageset/Contents.json
  Pinit/Pinit/Resources/Assets.xcassets/HISEHOONImg.imageset/HISEHOONImg.jpeg
  Pinit/Pinit/Resources/Assets.xcassets/Ikhwan0204Img.imageset/Contents.json
  Pinit/Pinit/Resources/Assets.xcassets/Ikhwan0204Img.imageset/Ikhwan0204Img.png
  Pinit/Pinit/Resources/Assets.xcassets/IntakHan304Img.imageset/Contents.json
  Pinit/Pinit/Resources/Assets.xcassets/IntakHan304Img.imageset/IntakHan304Img.png
  Pinit/Pinit/Resources/Assets.xcassets/JustHMImg.imageset/Contents.json
  Pinit/Pinit/Resources/Assets.xcassets/JustHMImg.imageset/JustHMImg.jpeg
  Pinit/Pinit/Resources/Assets.xcassets/kut7728Img.imageset/Contents.json
  Pinit/Pinit/Resources/Assets.xcassets/kut7728Img.imageset/kut7728Img.png
  Pinit/Pinit/Views/Setting/ProducerCollectionViewCell.swift
  Pinit/Pinit/Views/Setting/SettingViewController.swift
Labels: FEAT

#21 Feature/#20 프로필 수정
  Pinit/Pinit/Models/ProducerEntity.swift
  Pinit/Pinit/Views/Setting/ProducerCollectionViewCell.swift
  Pinit/Pinit/Views/Setting/SettingViewController.swift
Labels: CHORE

#24 PinEditViewController 코드 정리
  Pinit/Pinit/Views/PinEdit/PinEditViewController.swift
Labels: FEAT

#28 [FIX] #25 Rematching PinEditVC and Add ViewType on Variables
  Pinit/Pinit/Views/PastPin/PastPinViewController.swift
  Pinit/Pinit/Views/PinEdit/PinEditViewController.swift
Labels: FIX

#32 화면 연결 및 데이터 흐름 작업
  Pinit/Pinit/Models/PinEntity.swift
  Pinit/Pinit/Models/ProducerEntity.swift
  Pinit/Pinit/Views/Home/CustomAnnotationView.swift
  Pinit/Pinit/Views/Home/CustomClusterAnnotationView.swift
  Pinit/Pinit/Views/Home/HomeViewController.swift
  Pinit/Pinit/Views/Home/PinRecordCell.swift
  Pinit/Pinit/Views/PastPin/PastPinViewController.swift
  Pinit/Pinit/Views/PinDetail/PinDetailViewController.swift
  Pinit/Pinit/Views/PinEdit/PinEditViewController.swift
Labels: FEAT

#34 [FEAT] Fix almost errors and data handling with HMM
  Pinit/Pinit/Extensions/Extension_UIViewController.swift
  Pinit/Pinit/Views/Home/CustomBottomSheet.swift
  Pinit/Pinit/Views/Home/HomeViewController.swift
  Pinit/Pinit/Views/Home/PinCollectionViewAdapter.swift
  Pinit/Pinit/Views/Home/PinRecordCell.swift
  Pinit/Pinit/Views/MainTabBarController.swift
  Pinit/Pinit/Views/PastPin/PastPinViewController.swift
  Pinit/Pinit/Views/PinDetail/PinDetailHeader.swift
  Pinit/Pinit/Views/PinDetail/PinDetailViewController.swift
  Pinit/Pinit/Views/PinEdit/PinEditViewController.swift
Labels: FEAT

#38 [FIX] Fix UI, Colors and delete Network.swift
  Pinit/Pinit/DesignSystem/DesignSystem.swift
  Pinit/Pinit/Repository/Moya/Network.swift
  Pinit/Pinit/Views/Cells/PinRecordCell.swift
  Pinit/Pinit/Views/Cells/ReviewCell.swift
  Pinit/Pinit/Views/Home/HomeViewController.swift
  Pinit/Pinit/Views/Home/SubViews/CustomBottomSheet.swift
  Pinit/Pinit/Views/PastPin/PastPinViewController.swift
  Pinit/Pinit/Views/PinDetail/PinDetailViewController.swift
  Pinit/Pinit/Views/PinDetail/SubViews/NewPinReviewPanel.swift
  Pinit/Pinit/Views/PinDetail/SubViews/PinDetailHeader.swift
  Pinit/Pinit/Views/PinEdit/PinEditViewController.swift
  Pinit/Pinit/Views/Setting/SettingViewController.swift
Labels: FIX
